### ISSUE TITLE
[Feature] Show completed todos button

### ISSUE THREAD

**Issue by teoh4770** [teoh4770/Pomotama#16]
- Create a "show completed todos" button 
- Click on the "show completed todos" button will populate the current todos with completed todos

**Comment by rohitsingh290320052** [comment]
Interested, please assign me

**Comment by mafzaldev** [comment]
Hi @teoh4770 , can you assign me this issue?

**Comment by teoh4770** [comment]
> Hi @teoh4770 , can you assign me this issue? 

Sure, no problem 🙏
Thanks for contributing

**Comment by mafzaldev** [comment]
> * show completed todos



> > Hi @teoh4770 , can you assign me this issue?
> 
> Sure, no problem 🙏 Thanks for contributing

I have a suggestion to resolve #17 in this issue, otherwise there may some inconsistencies with tasks list, while toggling.

**Comment by teoh4770** [comment]
Let's finish this issue first and see how it goes 🙏

**Comment by mafzaldev** [comment]
Submitted PR, please review.
