### ISSUE TITLE
[Improvement] UX improvement

### ISSUE THREAD

**Issue by teoh4770** [teoh4770/Pomotama#23]
"the improvements I would suggest is UX improvements. When adding new tasks you could tell what the number represents, it's after I added it then I saw that it represented "rounds" also the delete button wasn't really visible in my eye sight as I wasn't looking for it down in the bottom left of the card"

fix: can add tooltip after the todo edit label to provide suggestions to user. When user hover over the icon, he will know what to do

**Comment by teoh4770** [comment]
Note: can reorder the todo
Dragging the todo -> encourage prioritisation of certain todo + provides user more freedom

**Comment by teoh4770** [comment]
Update the favicon so that when the dark mode is trigger + timer start running, then the icon should turn gray

**Comment by teoh4770** [comment]
@mafzaldev can you help me handle this? I wanna see how would you implement the reorder feature.

> Note: can reorder the todo
>
> Dragging the todo -> encourage prioritisation of certain todo + provides user more freedom

**Comment by mafzaldev** [comment]
> @mafzaldev can you help me handle this? I wanna see how would you implement the reorder feature.
> 
> > Note: can reorder the todo
> > Dragging the todo -> encourage prioritisation of certain todo + provides user more freedom

Hi, to implement this feature, we can use `react-sortable-hoc` package. It comes with reordering functionality and animation. But still need to add some changes suitable to our use case.

https://github.com/clauderic/react-sortable-hoc

**Comment by imran-yasin** [comment]
Hi, @teoh4770 what do you think about the delete button now? 
![image](https://github.com/teoh4770/Pomotama/assets/98706646/027d1782-1d23-40f7-8a40-e2fd964bb80f)

**Comment by teoh4770** [comment]
I don't like delete button change, because it kinda clash the current design of the app itself.
Read the guideline by https://m2.material.io/components/buttons#theming to learn more about the button hierarchy.

Remove the red background for Delete button, and make the actions button in here **uppercase**.
![Screenshot 2024-05-06 at 10 10 46 AM](https://github.com/teoh4770/Pomotama/assets/98545971/08544f9c-1d67-4f0d-a4d4-d1dc764bd9f0)

**Comment by teoh4770** [comment]
After you fixed that, I will consider to let you work on reordering todo

**Comment by teoh4770** [comment]
@mafzaldev You can implement the reorder and swap feature for todos. Let me know if you need any help

**Comment by teoh4770** [comment]
> Hi, @teoh4770 what do you think about the delete button now? This is my first time open source contribution if there any suggestion do let me know and I loved the idea of the @mafzaldev regarding the reordering and swapping the task based on the priority it would be great if you allow me to implement this feature as well. Thank you 

- I don't like make the delete button more prominent than the save button
- Please refer to the best practice for button ui: https://m2.material.io/components/buttons#text-button
- Instead, i have made the changes by making the delete, cancel and save button uppercase, which help the buttons stand out

![Screenshot 2024-05-06 at 6 29 49 PM](https://github.com/teoh4770/Pomotama/assets/98545971/3cbaf504-4e24-4a1f-8de0-43a12a8a786d)

**Comment by mafzaldev** [comment]
The `react-sortable-hoc` was causing issues, so moved to another library [hello-pangea/dnd](https://github.com/hello-pangea/dnd) .
