### ISSUE TITLE
[Feature] Adding a description section in our todo 

### ISSUE THREAD

**Issue by teoh4770** [teoh4770/Pomotama#7]
Like a sticky note for our current todo, should be an improve textarea element that allowed formatting?
I am thinking about it supporting markdown, but maybe it is not necessary?

![Screenshot 2024-04-09 at 11 31 36 AM](https://github.com/teoh4770/Pomotama/assets/98545971/143fd31e-1629-4b85-8b12-df9c519f6ee6)

**Comment by anushkaDev9** [comment]
I want to work on this issue.

**Comment by teoh4770** [comment]
> I want to work on this issue.

Apologize for late reply @anushkaDev9 
Please go for it anytime. Let me know if you need any help with the code and the problem itself.
